services:
  next-app:
    container_name: console
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "${CORE_PORT:-80}:${CORE_PORT:-80}"
    environment:
      - CORE_PORT=${CORE_PORT:-80}
    restart: always
    networks:
      - dataherald_network
networks:
  dataherald_network:
    external: true
