version: "3.9"
services:
  web:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - app
    # ... you can set additional configurations like volumes for hot-reloading during development

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    command: uvicorn dataherald.app:app --host 0.0.0.0 --port 80 --log-config log_config.yml --log-level debug --reload
    stdin_open: true
    tty: true
    volumes:
      - ./dataherald:/app/dataherald
    depends_on:
      - db
      - mongodb
    networks:
      - backendnetwork
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
      - ./dbdata/mongo_data/data:/data/db/
      - ./dbdata/mongo_data/db_config:/data/configdb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGODB_DB_NAME}"
    networks:
      - backendnetwork

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backendnetwork
volumes:
  db:
    driver: local
networks:
  backendnetwork:
    external: true
