version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # Nginx will be accessible on port 80 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Assumes your custom Nginx configuration is in the `nginx/nginx.conf` file

    networks:
      - dataherald_network

networks:
  dataherald_network:
    external: true
